[package]
name = "lbin"
version = "0.1.0"
edition = "2024"
author = "sakura <mail.liminal@pm.me>"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive", "env"] }
colored = "3.0.0"
regex = "1.12.2"
